Script Executor:
  attributes:
    full_command:
      type: 'str'
      expected_max_len: 100
      default_value: null
      enable_env_var_input: true

Custom Configuration:
  attributes:
    configlet:
      type: 'str'
      expected_max_len: null
      default_value: null
      enable_env_var_input: false
    plane:
      type: 'str'
      options:
        - 'admin'
        - 'sdr'
      default_value: 'sdr'
    description:
      type: 'str'
      expected_max_len: 100
      default_value: ''
      enable_env_var_input: false
